spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 603014937589-elvqqerun1lfrlquo1l85em9vtpsd2dr.apps.googleusercontent.com
            client-secret: ${CLIENT_SECRET_GOOGLE}
            redirect-uri: http://localhost:8080/login/google-callback
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client_id: 8e1195f51d733edc8a79e51967b3065d
            redirect_uri: http://localhost:8080/login/kakao-callback
            authorization-grant-type: authorization_code
          naver:
            client-id: aZnt50bn3mhLRaHheH5O
            client-secret: ${CLIENT_SECRET_NAVER}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/naver-callback
        provider:
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

