spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          naver:
            client-id: aZnt50bn3mhLRaHheH5O
            client-secret: mW4dTzcQBW
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/naver-callback
          google:
            client-id: 603014937589-elvqqerun1lfrlquo1l85em9vtpsd2dr.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/google-callback
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
