spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true

#mail smtp 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
#    username: "j1y00n000301@gmail.com"
#    password: "ymal yxay rvzh uvxc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


